CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_number VARCHAR(50) NOT NULL UNIQUE,
    holder VARCHAR(100) NOT NULL,
    bank_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS banks (
    bankId BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL
);

INSERT INTO accounts (account_number, holder, bank_id, created_at) VALUES
('1001', 'Juan Pérez', 1, CURRENT_TIMESTAMP),
('1002', 'Ana Gómez', 2, CURRENT_TIMESTAMP),
('1003', 'Carlos Ruiz', 3, CURRENT_TIMESTAMP);
